DROP DATABASE IF EXISTS project_db;
CREATE DATABASE project_db;
DROP USER IF EXISTS project_user;
CREATE USER project_user WITH ENCRYPTED PASSWORD '0000';
GRANT ALL PRIVILEGES ON DATABASE project_db TO project_user;
